config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "good_job"

  get "changelog", to: "pages#changelog"
  get "feedback", to: "pages#feedback"
  get "early-access", to: "pages#early_access"

  resource :registration, only: %i[new create]
  resources :sessions, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]

  resources :users, only: %i[update destroy]

  resource :onboarding, only: :show do
    collection do
      get :profile
      get :preferences
    end
  end

  namespace :settings do
    resource :profile, only: :show
    resource :preferences, only: :show
    resource :hosting, only: %i[show update]
    resource :billing, only: :show
  end

  resource :subscription, only: %i[new show] do
    get :success, on: :collection
  end

  resources :tags, except: :show do
    resources :deletions, only: %i[new create], module: :tag
  end

  namespace :category do
    resource :dropdown, only: :show
  end

  resources :categories do
    resources :deletions, only: %i[new create], module: :category
  end

  resources :merchants, only: %i[index new create edit update destroy]

  namespace :account do
    resources :transfers, only: %i[new create destroy show update]
  end

  resources :imports, only: %i[index new show create destroy] do
    post :publish, on: :member

    resource :upload, only: %i[show update], module: :import
    resource :configuration, only: %i[show update], module: :import
    resource :clean, only: :show, module: :import
    resource :confirm, only: :show, module: :import

    resources :rows, only: %i[show update], module: :import
    resources :mappings, only: :update, module: :import
  end

  resources :accounts, only: %i[index new] do
    collection do
      get :summary
      get :list
      post :sync_all
    end

    member do
      post :sync
    end

    scope module: :account do
      resources :holdings, only: %i[index new show destroy]
      resources :cashes, only: :index

      resources :transactions, only: %i[index update]
      resources :valuations, only: %i[index new create]
      resources :trades, only: %i[index new create update] do
        get :securities, on: :collection
      end

      resources :entries, only: %i[index edit update show destroy]
    end
  end

  # Convenience routes for polymorphic paths
  # Example: account_path(Account.new(accountable: Depository.new)) => /depositories/123
  direct :account do |model, options|
    route_for model.accountable_name, model, options
  end
  direct :edit_account do |model, options|
    route_for "edit_#{model.accountable_name}", model, options
  end

  resources :depositories, except: :index
  resources :investments, except: :index
  resources :properties, except: :index
  resources :vehicles, except: :index
  resources :credit_cards, except: :index
  resources :loans, except: :index
  resources :cryptos, except: :index
  resources :other_assets, except: :index
  resources :other_liabilities, except: :index

  resources :transactions, only: %i[index new create] do
    collection do
      post "bulk_delete"
      get "bulk_edit"
      post "bulk_update"
      post "mark_transfers"
      post "unmark_transfers"
    end
  end

  resources :institutions, except: %i[index show] do
    post :sync, on: :member
  end
  resources :invite_codes, only: %i[index create]

  resources :issues, only: :show

  namespace :issue do
    resources :exchange_rate_provider_missings, only: :update
  end

  resources :invitations, only: [ :new, :create ] do
    get :accept, on: :member
  end

  # For managing self-hosted upgrades and release notifications
  resources :upgrades, only: [] do
    member do
      post :acknowledge
      post :deploy
    end
  end

  resources :currencies, only: %i[show]

  resources :impersonation_sessions, only: [ :create ] do
    post :join, on: :collection
    delete :leave, on: :collection

    member do
      put :approve
      put :reject
      put :complete
    end
  end

  # Stripe webhook endpoint
  post "webhooks/stripe", to: "webhooks#stripe"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/account.rb
class Account < ApplicationRecord
  include Syncable, Monetizable, Issuable

  validates :name, :balance, :currency, presence: true

  belongs_to :family
  belongs_to :institution, optional: true
  belongs_to :import, optional: true

  has_many :import_mappings, as: :mappable, dependent: :destroy, class_name: "Import::Mapping"
  has_many :entries, dependent: :destroy, class_name: "Account::Entry"
  has_many :transactions, through: :entries, source: :entryable, source_type: "Account::Transaction"
  has_many :valuations, through: :entries, source: :entryable, source_type: "Account::Valuation"
  has_many :trades, through: :entries, source: :entryable, source_type: "Account::Trade"
  has_many :holdings, dependent: :destroy
  has_many :balances, dependent: :destroy
  has_many :syncs, dependent: :destroy
  has_many :issues, as: :issuable, dependent: :destroy

  monetize :balance

  enum :classification, { asset: "asset", liability: "liability" }, validate: { allow_nil: true }

  scope :active, -> { where(is_active: true) }
  scope :assets, -> { where(classification: "asset") }
  scope :liabilities, -> { where(classification: "liability") }
  scope :alphabetically, -> { order(:name) }
  scope :ungrouped, -> { where(institution_id: nil) }

  has_one_attached :logo

  delegated_type :accountable, types: Accountable::TYPES, dependent: :destroy

  accepts_nested_attributes_for :accountable, update_only: true

  delegate :value, :series, to: :accountable

  class << self
    def by_group(period: Period.all, currency: Money.default_currency.iso_code)
      grouped_accounts = { assets: ValueGroup.new("Assets", currency), liabilities: ValueGroup.new("Liabilities", currency) }

      Accountable.by_classification.each do |classification, types|
        types.each do |type|
          accounts = self.where(accountable_type: type)
          if accounts.any?
            group = grouped_accounts[classification.to_sym].add_child_group(type, currency)
            accounts.each do |account|
              group.add_value_node(
                account,
                account.balance_money.exchange_to(currency, fallback_rate: 0),
                account.series(period: period, currency: currency)
              )
            end
          end
        end
      end

      grouped_accounts
    end

    def create_and_sync(attributes)
      attributes[:accountable_attributes] ||= {} # Ensure accountable is created, even if empty
      account = new(attributes)

      transaction do
        # Create 2 valuations for new accounts to establish a value history for users to see
        account.entries.build(
          name: "Current Balance",
          date: Date.current,
          amount: account.balance,
          currency: account.currency,
          entryable: Account::Valuation.new
        )
        account.entries.build(
          name: "Initial Balance",
          date: 1.day.ago.to_date,
          amount: 0,
          currency: account.currency,
          entryable: Account::Valuation.new
        )

        account.save!
      end

      account.sync_later
      account
    end
  end

  def original_balance
    balance_amount = balances.chronological.first&.balance || balance
    Money.new(balance_amount, currency)
  end

  def owns_ticker?(ticker)
    security_id = Security.find_by(ticker: ticker)&.id
    entries.account_trades
           .joins("JOIN account_trades ON account_entries.entryable_id = account_trades.id")
           .where(account_trades: { security_id: security_id }).any?
  end

  def favorable_direction
    classification == "asset" ? "up" : "down"
  end

  def update_with_sync!(attributes)
    transaction do
      update!(attributes)
      update_balance!(attributes[:balance]) if attributes[:balance]
    end

    sync_later
  end

  def update_balance!(balance)
    valuation = entries.account_valuations.find_by(date: Date.current)

    if valuation
      valuation.update! amount: balance
    else
      entries.create! \
        date: Date.current,
        amount: balance,
        currency: currency,
        entryable: Account::Valuation.new
    end
  end

  def holding_qty(security, date: Date.current)
    entries.account_trades
           .joins("JOIN account_trades ON account_entries.entryable_id = account_trades.id")
           .where(account_trades: { security_id: security.id })
           .where("account_entries.date <= ?", date)
           .sum("account_trades.qty")
  end
end

app/models/account/balance.rb
class Account::Balance < ApplicationRecord
  include Monetizable

  belongs_to :account
  validates :account, :date, :balance, presence: true
  monetize :balance
  scope :in_period, ->(period) { period.date_range.nil? ? all : where(date: period.date_range) }
  scope :chronological, -> { order(:date) }
end

app/models/account/balance/calculator.rb
class Account::Balance::Calculator
  def initialize(account, sync_start_date)
    @account = account
    @sync_start_date = sync_start_date
  end

  def calculate(is_partial_sync: false)
    cached_entries = account.entries.where("date >= ?", sync_start_date).to_a
    sync_starting_balance = is_partial_sync ? find_start_balance_for_partial_sync : find_start_balance_for_full_sync(cached_entries)

    prior_balance = sync_starting_balance

    (sync_start_date..Date.current).map do |date|
      current_balance = calculate_balance_for_date(date, entries: cached_entries, prior_balance:)

      prior_balance = current_balance

      build_balance(date, current_balance)
    end
  end

  private
    attr_reader :account, :sync_start_date

    def find_start_balance_for_partial_sync
      account.balances.find_by(currency: account.currency, date: sync_start_date - 1.day)&.balance
    end

    def find_start_balance_for_full_sync(cached_entries)
      account.balance + net_entry_flows(cached_entries.select { |e| e.account_transaction? })
    end

    def calculate_balance_for_date(date, entries:, prior_balance:)
      valuation = entries.find { |e| e.date == date && e.account_valuation? }

      return valuation.amount if valuation

      entries = entries.select { |e| e.date == date }

      prior_balance - net_entry_flows(entries)
    end

    def net_entry_flows(entries, target_currency = account.currency)
      converted_entry_amounts = entries.map { |t| t.amount_money.exchange_to(target_currency, date: t.date) }

      flows = converted_entry_amounts.sum(&:amount)

      account.liability? ? flows * -1 : flows
    end

    def build_balance(date, balance, currency = nil)
      account.balances.build \
        date: date,
        balance: balance,
        currency: currency || account.currency
    end
end

app/models/account/balance/converter.rb
class Account::Balance::Converter
  def initialize(account, sync_start_date)
    @account = account
    @sync_start_date = sync_start_date
  end

  def convert(balances)
    calculate_converted_balances(balances)
  end

  private
    attr_reader :account, :sync_start_date

    def calculate_converted_balances(balances)
      from_currency = account.currency
      to_currency = account.family.currency

      if ExchangeRate.exchange_rates_provider.nil?
        account.observe_missing_exchange_rate_provider
        return []
      end

      exchange_rates = ExchangeRate.find_rates from: from_currency,
                                               to: to_currency,
                                               start_date: sync_start_date

      missing_exchange_rates = balances.map(&:date) - exchange_rates.map(&:date)

      if missing_exchange_rates.any?
        account.observe_missing_exchange_rates(from: from_currency, to: to_currency, dates: missing_exchange_rates)
        return []
      end

      balances.map do |balance|
        exchange_rate = exchange_rates.find { |er| er.date == balance.date }
        build_balance(balance.date, exchange_rate.rate * balance.balance, to_currency)
      end
    end

    def build_balance(date, balance, currency = nil)
      account.balances.build \
        date: date,
        balance: balance,
        currency: currency || account.currency
    end
end

app/models/account/balance/loader.rb
class Account::Balance::Loader
  def initialize(account)
    @account = account
  end

  def load(balances, start_date)
    Account::Balance.transaction do
      upsert_balances!(balances)
      purge_stale_balances!(start_date)

      account.reload

      update_account_balance!(balances)
    end
  end

  private
    attr_reader :account

    def update_account_balance!(balances)
      last_balance = balances.select { |db| db.currency == account.currency }.last&.balance
      account.update! balance: last_balance if last_balance.present?
    end

    def upsert_balances!(balances)
      current_time = Time.now
      balances_to_upsert = balances.map do |balance|
        balance.attributes.slice("date", "balance", "currency").merge("updated_at" => current_time)
      end

      account.balances.upsert_all(balances_to_upsert, unique_by: %i[account_id date currency])
    end

    def purge_stale_balances!(start_date)
      account.balances.delete_by("date < ?", start_date)
    end
end

app/models/account/balance/syncer.rb
class Account::Balance::Syncer
  def initialize(account, start_date: nil)
    @account = account
    @provided_start_date = start_date
    @sync_start_date = calculate_sync_start_date(start_date)
    @loader = Account::Balance::Loader.new(account)
    @converter = Account::Balance::Converter.new(account, sync_start_date)
    @calculator = Account::Balance::Calculator.new(account, sync_start_date)
  end

  def run
    daily_balances = calculator.calculate(is_partial_sync: is_partial_sync?)
    daily_balances += converter.convert(daily_balances) if account.currency != account.family.currency

    loader.load(daily_balances, account_start_date)
  rescue Money::ConversionError => e
    account.observe_missing_exchange_rates(from: e.from_currency, to: e.to_currency, dates: [ e.date ])
  end

  private

    attr_reader :sync_start_date, :provided_start_date, :account, :loader, :converter, :calculator

    def account_start_date
      @account_start_date ||= begin
                                oldest_entry = account.entries.chronological.first

                                return Date.current unless oldest_entry.present?

                                if oldest_entry.account_valuation?
                                  oldest_entry.date
                                else
                                  oldest_entry.date - 1.day
                                end
                              end
    end

    def calculate_sync_start_date(provided_start_date)
      return provided_start_date if provided_start_date.present? && prior_balance_available?(provided_start_date)

      account_start_date
    end

    def prior_balance_available?(date)
      account.balances.find_by(currency: account.currency, date: date - 1.day).present?
    end

    def is_partial_sync?
      sync_start_date == provided_start_date && sync_start_date < Date.current
    end
end

app/models/account/entry_builder.rb
class Account::EntryBuilder
  include ActiveModel::Model

  TYPES = %w[income expense buy sell interest transfer_in transfer_out].freeze

  attr_accessor :type, :date, :qty, :ticker, :price, :amount, :currency, :account, :transfer_account_id

  validates :type, inclusion: { in: TYPES }

  def save
    if valid?
      create_builder.save
    end
  end

  private

    def create_builder
      case type
      when "buy", "sell"
        create_trade_builder
      else
        create_transaction_builder
      end
    end

    def create_trade_builder
      Account::TradeBuilder.new \
        type: type,
        date: date,
        qty: qty,
        ticker: ticker,
        price: price,
        account: account
    end

    def create_transaction_builder
      Account::TransactionBuilder.new \
        type: type,
        date: date,
        amount: amount,
        account: account,
        transfer_account_id: transfer_account_id
    end
end

app/models/account/entryable.rb
module Account::Entryable
  extend ActiveSupport::Concern

  TYPES = %w[Account::Valuation Account::Transaction Account::Trade]

  def self.from_type(entryable_type)
    entryable_type.presence_in(TYPES).constantize
  end

  included do
    has_one :entry, as: :entryable, touch: true
  end
end

app/controllers/account/cashes_controller.rb
class Account::CashesController < ApplicationController
  layout :with_sidebar

  before_action :set_account

  def index
  end

  private

    def set_account
      @account = Current.family.accounts.find(params[:account_id])
    end
end

app/views/accounts/show/_activity.html.erb
<%# locals: (account:) %>

<%= turbo_frame_tag dom_id(account, :entries), src: account_entries_path(account) do %>
  <%= render "account/entries/loading" %>
<% end %>

app/views/accounts/show/_chart.html.erb
<%# locals: (account:, title: nil, tooltip: nil) %>

<% period = Period.from_param(params[:period]) %>
<% series = account.series(period: period) %>
<% trend = series.trend %>
<% default_value_title = account.asset? ? t(".balance") : t(".owed") %>

<div class="bg-white shadow-xs rounded-xl border border-alpha-black-25 rounded-lg">
  <div class="p-4 flex justify-between">
    <div class="space-y-2">
      <div class="flex items-center gap-1">
        <%= tag.p title || default_value_title, class: "text-sm font-medium text-gray-500" %>
        <%= tooltip %>
      </div>

      <%= tag.p format_money(account.value), class: "text-gray-900 text-3xl font-medium" %>

      <div>
        <% if trend.direction.flat? %>
          <%= tag.span t(".no_change"), class: "text-gray-500" %>
        <% else %>
          <%= tag.span "#{trend.value.positive? ? "+" : ""}#{format_money(trend.value)}", style: "color: #{trend.color}" %>
          <% unless trend.percent.infinite? %>
            <%= tag.span "(#{trend.percent}%)", style: "color: #{trend.color}" %>
          <% end %>
        <% end %>

        <%= tag.span period_label(period), class: "text-gray-500" %>
      </div>
    </div>

    <%= form_with url: request.path, method: :get, data: { controller: "auto-submit-form" } do |form| %>
      <%= period_select form: form, selected: period.name %>
    <% end %>
  </div>

  <div class="h-64 flex items-center justify-center text-2xl font-bold">
    <%= render "shared/line_chart", series: series %>
  </div>
</div>

app/views/accounts/show/_header.html.erb
<%# locals: (account:, title: nil, subtitle: nil) %>

<header class="space-y-4">
  <div class="flex items-center gap-4">
    <% content = yield %>

    <% if content.present? %>
      <%= content %>
    <% else %>
      <div class="flex items-center gap-3">
        <%= render "accounts/logo", account: account %>

        <div>
          <h2 class="font-medium text-xl"><%= title || account.name %></h2>
          <% if subtitle.present? %>
            <p class="text-sm text-gray-500"><%= subtitle %></p>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="flex items-center gap-3 ml-auto">
      <%= button_to sync_account_path(account), method: :post, class: "flex items-center gap-2", title: "Sync Account" do %>
        <%= lucide_icon "refresh-cw", class: "w-4 h-4 text-gray-500 hover:text-gray-400" %>
      <% end %>

      <%= render "accounts/show/menu", account: account %>
    </div>
  </div>

  <% if account.highest_priority_issue %>
    <%= render partial: "issues/issue", locals: { issue: account.highest_priority_issue } %>
  <% end %>
</header>

app/views/accounts/show/_loading.html.erb
<div class="p-5">
  <p class="text-gray-500 animate-pulse">Loading account...</p>
</div>

app/views/accounts/show/_menu.html.erb
<%# locals: (account:) %>

<%= contextual_menu do %>
  <div class="w-48 p-1 text-sm leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
    <%= link_to edit_account_path(account),
                      data: { turbo_frame: :modal },
                      class: "block w-full py-2 px-3 space-x-2 text-gray-900 hover:bg-gray-50 flex items-center rounded-lg" do %>
      <%= lucide_icon "pencil-line", class: "w-5 h-5 text-gray-500" %>

      <span><%= t(".edit") %></span>
    <% end %>

    <%= link_to new_import_path,
                      data: { turbo_frame: :modal },
                      class: "block w-full py-2 px-3 space-x-2 text-gray-900 hover:bg-gray-50 flex items-center rounded-lg" do %>
      <%= lucide_icon "download", class: "w-5 h-5 text-gray-500" %>

      <span><%= t(".import") %></span>
    <% end %>

    <%= button_to account_path(account),
                        method: :delete,
                        class: "block w-full py-2 px-3 space-x-2 text-red-600 hover:bg-red-50 flex items-center rounded-lg",
                        data: {
                          turbo_frame: :_top,
                          turbo_confirm: {
                            title: t(".confirm_title"),
                            body: t(".confirm_body_html"),
                            accept: t(".confirm_accept", name: account.name)
                          }
                        } do %>
      <%= lucide_icon("trash-2", class: "w-5 h-5 mr-2") %> Delete account
    <% end %>
  </div>
<% end %>

app/views/accounts/show/_tab.html.erb
<%# locals: (account:, key:, is_selected:) %>

<%= link_to key.titleize,
            account_path(account, tab: key),
            class: [
              "px-2 py-1.5 rounded-md border border-transparent",
              "bg-white shadow-xs border-alpha-black-50": is_selected
            ] %>

app/views/accounts/show/_tabs.html.erb
<%# locals: (account:, tabs:) %>

<% selected_tab = tabs.find { |tab| tab[:key] == params[:tab] } || tabs.first %>

<div class="flex gap-2 text-sm text-gray-900 font-medium mb-4">
  <% tabs.each do |tab| %>
    <%= render "accounts/show/tab", account: account, key: tab[:key], is_selected: selected_tab[:key] == tab[:key] %>
  <% end %>
</div>

<%= selected_tab[:contents] %>

app/views/accounts/show/_template.html.erb
<%# locals: (account:, header: nil, chart: nil, tabs: nil) %>

<%= turbo_stream_from account %>

<%= turbo_frame_tag dom_id(account) do %>
  <%= tag.div class: "space-y-4" do %>
    <% if header.present? %>
      <%= header %>
    <% else %>
      <%= render "accounts/show/header", account: account %>
    <% end %>

    <% if chart.present? %>
      <%= chart %>
    <% else %>
      <%= render "accounts/show/chart", account: account %>
    <% end %>

    <div class="min-h-[800px]">
      <% if tabs.present? %>
        <%= tabs %>
      <% else %>
        <%= render "accounts/show/activity", account: account %>
      <% end %>
    </div>
  <% end %>
<% end %>