config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "good_job"

  get "changelog", to: "pages#changelog"
  get "feedback", to: "pages#feedback"
  get "early-access", to: "pages#early_access"

  resource :registration, only: %i[new create]
  resources :sessions, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]

  resources :users, only: %i[update destroy]

  resource :onboarding, only: :show do
    collection do
      get :profile
      get :preferences
    end
  end

  namespace :settings do
    resource :profile, only: :show
    resource :preferences, only: :show
    resource :hosting, only: %i[show update]
    resource :billing, only: :show
  end

  resource :subscription, only: %i[new show] do
    get :success, on: :collection
  end

  resources :tags, except: :show do
    resources :deletions, only: %i[new create], module: :tag
  end

  namespace :category do
    resource :dropdown, only: :show
  end

  resources :categories do
    resources :deletions, only: %i[new create], module: :category
  end

  resources :merchants, only: %i[index new create edit update destroy]

  namespace :account do
    resources :transfers, only: %i[new create destroy show update]
  end

  resources :imports, only: %i[index new show create destroy] do
    post :publish, on: :member

    resource :upload, only: %i[show update], module: :import
    resource :configuration, only: %i[show update], module: :import
    resource :clean, only: :show, module: :import
    resource :confirm, only: :show, module: :import

    resources :rows, only: %i[show update], module: :import
    resources :mappings, only: :update, module: :import
  end

  resources :accounts, only: %i[index new] do
    collection do
      get :summary
      get :list
      post :sync_all
    end

    member do
      post :sync
    end

    scope module: :account do
      resources :holdings, only: %i[index new show destroy]
      resources :cashes, only: :index

      resources :transactions, only: %i[index update]
      resources :valuations, only: %i[index new create]
      resources :trades, only: %i[index new create update] do
        get :securities, on: :collection
      end

      resources :entries, only: %i[index edit update show destroy]
    end
  end

  # Convenience routes for polymorphic paths
  # Example: account_path(Account.new(accountable: Depository.new)) => /depositories/123
  direct :account do |model, options|
    route_for model.accountable_name, model, options
  end
  direct :edit_account do |model, options|
    route_for "edit_#{model.accountable_name}", model, options
  end

  resources :depositories, except: :index
  resources :investments, except: :index
  resources :properties, except: :index
  resources :vehicles, except: :index
  resources :credit_cards, except: :index
  resources :loans, except: :index
  resources :cryptos, except: :index
  resources :other_assets, except: :index
  resources :other_liabilities, except: :index

  resources :transactions, only: %i[index new create] do
    collection do
      post "bulk_delete"
      get "bulk_edit"
      post "bulk_update"
      post "mark_transfers"
      post "unmark_transfers"
    end
  end

  resources :institutions, except: %i[index show] do
    post :sync, on: :member
  end
  resources :invite_codes, only: %i[index create]

  resources :issues, only: :show

  namespace :issue do
    resources :exchange_rate_provider_missings, only: :update
  end

  resources :invitations, only: [ :new, :create ] do
    get :accept, on: :member
  end

  # For managing self-hosted upgrades and release notifications
  resources :upgrades, only: [] do
    member do
      post :acknowledge
      post :deploy
    end
  end

  resources :currencies, only: %i[show]

  resources :impersonation_sessions, only: [ :create ] do
    post :join, on: :collection
    delete :leave, on: :collection

    member do
      put :approve
      put :reject
      put :complete
    end
  end

  # Stripe webhook endpoint
  post "webhooks/stripe", to: "webhooks#stripe"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :family
  has_many :taggings, dependent: :destroy
  has_many :transactions, through: :taggings, source: :taggable, source_type: "Account::Transaction"
  has_many :import_mappings, as: :mappable, dependent: :destroy, class_name: "Import::Mapping"

  validates :name, presence: true, uniqueness: { scope: :family }

  scope :alphabetically, -> { order(:name) }

  COLORS = %w[#e99537 #4da568 #6471eb #db5a54 #df4e92 #c44fe9 #eb5429 #61c9ea #805dee #6ad28a]

  UNCATEGORIZED_COLOR = "#737373"

  def replace_and_destroy!(replacement)
    transaction do
      raise ActiveRecord::RecordInvalid, "Replacement tag cannot be the same as the tag being destroyed" if replacement == self

      if replacement
        taggings.update_all tag_id: replacement.id
      end

      destroy!
    end
  end
end

app/controllers/tag/deletions_controller.rb
class Tag::DeletionsController < ApplicationController
  layout :with_sidebar

  before_action :set_tag
  before_action :set_replacement_tag, only: :create

  def new
  end

  def create
    @tag.replace_and_destroy! @replacement_tag
    redirect_back_or_to tags_path, notice: t(".deleted")
  end

  private

    def set_tag
      @tag = Current.family.tags.find_by(id: params[:tag_id])
    end

    def set_replacement_tag
      @replacement_tag = Current.family.tags.find_by(id: params[:replacement_tag_id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout :with_sidebar

  before_action :set_tag, only: %i[edit update destroy]

  def index
    @tags = Current.family.tags.alphabetically
  end

  def new
    @tag = Current.family.tags.new color: Tag::COLORS.sample
  end

  def create
    @tag = Current.family.tags.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: t(".created")
    else
      redirect_to tags_path, alert: t(".error", error: @tag.errors.full_messages.to_sentence)
    end
  end

  def edit
  end

  def update
    @tag.update!(tag_params)
    redirect_to tags_path, notice: t(".updated")
  end

  def destroy
    @tag.destroy!
    redirect_to tags_path, notice: t(".deleted")
  end

  private

    def set_tag
      @tag = Current.family.tags.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name, :color)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
  def null_tag
    Tag.new \
      name: "Uncategorized",
      color: Tag::UNCATEGORIZED_COLOR
  end
end

app/views/tags/_badge.html.erb
<%# locals: (tag:) %>
<% tag ||= null_category %>

<span class="border text-sm font-medium px-2.5 py-1 rounded-full content-center"
      style="
      background-color: color-mix(in srgb, <%= tag.color %> 5%, white);
        border-color: color-mix(in srgb, <%= tag.color %> 10%, white);
        color: <%= tag.color %>;">
  <%= tag.name %>
</span>

app/views/tags/_form.html.erb
<div data-controller="color-avatar">
  <%= styled_form_with model: tag, class: "space-y-4", data: { turbo_frame: :_top } do |f| %>
    <section class="space-y-4">
      <div class="w-fit m-auto">
        <%= render partial: "shared/color_avatar", locals: { name: tag.name, color: tag.color } %>
      </div>
      <div class="flex gap-2 items-center justify-center">
        <% Tag::COLORS.each do |color| %>
          <label class="relative">
            <%= f.radio_button :color, color, class: "sr-only peer", data: { action: "change->color-avatar#handleColorChange" } %>
            <div class="w-6 h-6 rounded-full cursor-pointer peer-checked:ring-2 peer-checked:ring-offset-2 peer-checked:ring-blue-500" style="background-color: <%= color %>"></div>
          </label>
        <% end %>
      </div>
      <div class="relative flex items-center border border-gray-200 rounded-lg">
        <%= f.text_field :name, placeholder: t(".placeholder"), autofocus: true, required: true, data: { color_avatar_target: "name" } %>
      </div>
    </section>

    <section>
      <%= hidden_field_tag :tag_id, params[:tag_id] %>
      <%= f.submit %>
    </section>
  <% end %>
</div>

app/views/tags/_ruler.html.erb
<div class="bg-white">
  <div class="h-px bg-alpha-black-50 ml-4 mr-6"></div>
</div>

app/views/tags/_tag.html.erb
<%# locals: (tag:) %>

<div id="<%= dom_id(tag) %>" class="flex justify-between items-center p-4 bg-white">
  <div class="flex w-full items-center gap-2.5">
    <%= render partial: "shared/color_avatar", locals: { name: tag.name, color: tag.color } %>
    <p class="text-gray-900 text-sm truncate">
      <%= tag.name %>
    </p>
  </div>
  <div class="justify-self-end">
    <%= contextual_menu do %>
      <div class="w-48 p-1 text-sm leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
        <%= contextual_menu_modal_action_item t(".edit"), edit_tag_path(tag) %>

        <% if tag.transactions.any? %>
          <%= link_to new_tag_deletion_path(tag),
                    class: "block w-full py-2 px-3 space-x-2 text-red-600 hover:bg-red-50 flex items-center rounded-lg",
                    data: { turbo_frame: :modal } do %>
            <%= lucide_icon "trash-2", class: "w-5 h-5" %>
            <span><%= t(".delete") %></span>
          <% end %>
        <% else %>
          <%= contextual_menu_destructive_item t(".delete"), tag_path(tag), turbo_confirm: nil %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tags/edit.html.erb
<%= modal_form_wrapper title: t(".edit") do %>
  <%= render "form", tag: @tag %>
<% end %>

app/views/tags/index.html.erb
<% content_for :sidebar do %>
  <%= render "settings/nav" %>
<% end %>

<section class="space-y-4">
  <header class="flex items-center justify-between">
    <h1 class="text-gray-900 text-xl font-medium"><%= t(".tags") %></h1>

    <%= link_to new_tag_path, class: "btn btn--primary flex items-center gap-1 justify-center", data: { turbo_frame: :modal } do %>
      <%= lucide_icon "plus", class: "w-5 h-5" %>
      <p><%= t(".new") %></p>
    <% end %>
  </header>

  <div class="bg-white shadow-xs border border-alpha-black-25 rounded-xl p-4">
    <% if @tags.any? %>
      <div class="rounded-xl bg-gray-25 space-y-1 p-1">
        <div class="flex items-center gap-1.5 px-4 py-2 text-xs font-medium text-gray-500 uppercase">
          <p><%= t(".tags") %></p>
          <span class="text-gray-400">&middot;</span>
          <p><%= @tags.count %></p>
        </div>

        <div class="border border-alpha-black-25 rounded-md bg-white shadow-xs">
          <div class="overflow-hidden rounded-md">
            <%= render partial: @tags, spacer_template: "tags/ruler" %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="flex justify-center items-center py-20">
        <div class="text-center flex flex-col items-center max-w-[300px]">
          <p class="text-gray-900 mb-1 font-medium text-sm"><%= t(".empty") %></p>
          <%= link_to new_tag_path, class: "w-fit flex text-white text-sm font-medium items-center gap-1 bg-gray-900 rounded-lg p-2 pr-3", data: { turbo_frame: "modal" } do %>
            <%= lucide_icon("plus", class: "w-5 h-5") %>
            <span><%= t(".new") %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= settings_nav_footer %>
</section>

app/views/tags/new.html.erb
<%= modal_form_wrapper title: t(".new") do %>
  <%= render "form", tag: @tag %>
<% end %>