config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "good_job"

  get "changelog", to: "pages#changelog"
  get "feedback", to: "pages#feedback"
  get "early-access", to: "pages#early_access"

  resource :registration, only: %i[new create]
  resources :sessions, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]

  resources :users, only: %i[update destroy]

  resource :onboarding, only: :show do
    collection do
      get :profile
      get :preferences
    end
  end

  namespace :settings do
    resource :profile, only: :show
    resource :preferences, only: :show
    resource :hosting, only: %i[show update]
    resource :billing, only: :show
  end

  resource :subscription, only: %i[new show] do
    get :success, on: :collection
  end

  resources :tags, except: :show do
    resources :deletions, only: %i[new create], module: :tag
  end

  namespace :category do
    resource :dropdown, only: :show
  end

  resources :categories do
    resources :deletions, only: %i[new create], module: :category
  end

  resources :merchants, only: %i[index new create edit update destroy]

  namespace :account do
    resources :transfers, only: %i[new create destroy show update]
  end

  resources :imports, only: %i[index new show create destroy] do
    post :publish, on: :member

    resource :upload, only: %i[show update], module: :import
    resource :configuration, only: %i[show update], module: :import
    resource :clean, only: :show, module: :import
    resource :confirm, only: :show, module: :import

    resources :rows, only: %i[show update], module: :import
    resources :mappings, only: :update, module: :import
  end

  resources :accounts, only: %i[index new] do
    collection do
      get :summary
      get :list
      post :sync_all
    end

    member do
      post :sync
    end

    scope module: :account do
      resources :holdings, only: %i[index new show destroy]
      resources :cashes, only: :index

      resources :transactions, only: %i[index update]
      resources :valuations, only: %i[index new create]
      resources :trades, only: %i[index new create update] do
        get :securities, on: :collection
      end

      resources :entries, only: %i[index edit update show destroy]
    end
  end

  # Convenience routes for polymorphic paths
  # Example: account_path(Account.new(accountable: Depository.new)) => /depositories/123
  direct :account do |model, options|
    route_for model.accountable_name, model, options
  end
  direct :edit_account do |model, options|
    route_for "edit_#{model.accountable_name}", model, options
  end

  resources :depositories, except: :index
  resources :investments, except: :index
  resources :properties, except: :index
  resources :vehicles, except: :index
  resources :credit_cards, except: :index
  resources :loans, except: :index
  resources :cryptos, except: :index
  resources :other_assets, except: :index
  resources :other_liabilities, except: :index

  resources :transactions, only: %i[index new create] do
    collection do
      post "bulk_delete"
      get "bulk_edit"
      post "bulk_update"
      post "mark_transfers"
      post "unmark_transfers"
    end
  end

  resources :institutions, except: %i[index show] do
    post :sync, on: :member
  end
  resources :invite_codes, only: %i[index create]

  resources :issues, only: :show

  namespace :issue do
    resources :exchange_rate_provider_missings, only: :update
  end

  resources :invitations, only: [ :new, :create ] do
    get :accept, on: :member
  end

  # For managing self-hosted upgrades and release notifications
  resources :upgrades, only: [] do
    member do
      post :acknowledge
      post :deploy
    end
  end

  resources :currencies, only: %i[show]

  resources :impersonation_sessions, only: [ :create ] do
    post :join, on: :collection
    delete :leave, on: :collection

    member do
      put :approve
      put :reject
      put :complete
    end
  end

  # Stripe webhook endpoint
  post "webhooks/stripe", to: "webhooks#stripe"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions, dependent: :nullify, class_name: "Account::Transaction"
  has_many :import_mappings, as: :mappable, dependent: :destroy, class_name: "Import::Mapping"
  belongs_to :family

  validates :name, :color, :family, presence: true
  validates :name, uniqueness: { scope: :family_id }

  before_update :clear_internal_category, if: :name_changed?

  scope :alphabetically, -> { order(:name) }

  COLORS = %w[#e99537 #4da568 #6471eb #db5a54 #df4e92 #c44fe9 #eb5429 #61c9ea #805dee #6ad28a]

  UNCATEGORIZED_COLOR = "#737373"

  DEFAULT_CATEGORIES = [
    { internal_category: "income", color: COLORS[0] },
    { internal_category: "food_and_drink", color: COLORS[1] },
    { internal_category: "entertainment", color: COLORS[2] },
    { internal_category: "personal_care", color: COLORS[3] },
    { internal_category: "general_services", color: COLORS[4] },
    { internal_category: "auto_and_transport", color: COLORS[5] },
    { internal_category: "rent_and_utilities", color: COLORS[6] },
    { internal_category: "home_improvement", color: COLORS[7] }
  ]

  def self.create_default_categories(family)
    if family.categories.size > 0
      raise ArgumentError, "Family already has some categories"
    end

    family_id = family.id
    categories = self::DEFAULT_CATEGORIES.map { |c| {
      name: I18n.t("transaction.default_category.#{c[:internal_category]}"),
      internal_category: c[:internal_category],
      color: c[:color],
      family_id:
    } }
    self.insert_all(categories)
  end

  def replace_and_destroy!(replacement)
    transaction do
      transactions.update_all category_id: replacement&.id
      destroy!
    end
  end

  private

    def clear_internal_category
      self.internal_category = nil
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout :with_sidebar

  before_action :set_category, only: %i[edit update destroy]
  before_action :set_transaction, only: :create

  def index
    @categories = Current.family.categories.alphabetically
  end

  def new
    @category = Current.family.categories.new color: Category::COLORS.sample
  end

  def create
    @category = Current.family.categories.new(category_params)

    if @category.save
      @transaction.update(category_id: @category.id) if @transaction
      redirect_back_or_to transactions_path, notice: t(".success")
    else
      redirect_back_or_to transactions_path, alert: t(".failure", error: @category.errors.full_messages.to_sentence)
    end
  end

  def edit
  end

  def update
    @category.update! category_params

    redirect_back_or_to transactions_path, notice: t(".success")
  end

  def destroy
    @category.destroy

    redirect_back_or_to categories_path, notice: t(".success")
  end

  private
    def set_category
      @category = Current.family.categories.find(params[:id])
    end

    def set_transaction
      if params[:transaction_id].present?
        @transaction = Current.family.transactions.find(params[:transaction_id])
      end
    end

    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/category/deletions_controller.rb
class Category::DeletionsController < ApplicationController
  layout :with_sidebar

  before_action :set_category
  before_action :set_replacement_category, only: :create

  def new
  end

  def create
    @category.replace_and_destroy! @replacement_category

    redirect_back_or_to transactions_path, notice: t(".success")
  end

  private
    def set_category
      @category = Current.family.categories.find(params[:category_id])
    end

    def set_replacement_category
      if params[:replacement_category_id].present?
        @replacement_category = Current.family.categories.find(params[:replacement_category_id])
      end
    end
end

app/controllers/category/dropdowns_controller.rb
class Category::DropdownsController < ApplicationController
  before_action :set_from_params

  def show
    @categories = categories_scope.to_a.excluding(@selected_category).prepend(@selected_category).compact
  end

  private
    def set_from_params
      if params[:category_id]
        @selected_category = categories_scope.find(params[:category_id])
      end

      if params[:transaction_id]
        @transaction = Current.family.transactions.find(params[:transaction_id])
      end
    end

    def categories_scope
      Current.family.categories.alphabetically
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def null_category
    Category.new \
      name: "Uncategorized",
      color: Category::UNCATEGORIZED_COLOR
  end

  def family_categories
    [ null_category ].concat(Current.family.categories.alphabetically)
  end
end

app/views/categories/_badge.html.erb
<%# locals: (category:) %>
<% category ||= null_category %>

<div>
  <span class="flex items-center gap-1 text-sm font-medium rounded-full px-1.5 py-1 border"
        style="
          background-color: color-mix(in srgb, <%= category.color %> 5%, white);
          border-color: color-mix(in srgb, <%= category.color %> 30%, white);
          color: <%= category.color %>;">
    <%= category.name %>
  </span>
</div>

app/views/categories/_category.html.erb
<%# locals: (category:) %>

<div id="<%= dom_id(category) %>" class="flex justify-between items-center p-4 bg-white">
  <div class="flex w-full items-center gap-2.5">
    <%= render partial: "categories/badge", locals: { category: category } %>
  </div>
  <div class="justify-self-end">
    <%= contextual_menu do %>
      <div class="w-48 p-1 text-sm leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
        <%= contextual_menu_modal_action_item t(".edit"), edit_category_path(category) %>

        <% if category.transactions.any? %>
          <%= link_to new_category_deletion_path(category),
              class: "flex items-center w-full rounded-lg text-red-600 hover:bg-red-50 py-2 px-3 gap-2",
              data: { turbo_frame: :modal } do %>
            <%= lucide_icon "trash-2", class: "shrink-0 w-5 h-5" %>
            <span class="text-sm"><%= t(".delete") %></span>
          <% end %>
        <% else %>
          <%= contextual_menu_destructive_item t(".delete"), category_path(category), turbo_confirm: nil %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<div data-controller="color-avatar">
  <%= styled_form_with model: category, class: "space-y-4", data: { turbo_frame: :_top } do |f| %>
    <section class="space-y-4">
      <div class="w-fit m-auto">
        <%= render partial: "shared/color_avatar", locals: { name: category.name, color: category.color } %>
      </div>
      <div class="flex gap-2 items-center justify-center">
        <% Category::COLORS.each do |color| %>
          <label class="relative">
            <%= f.radio_button :color, color, class: "sr-only peer", data: { action: "change->color-avatar#handleColorChange" } %>
            <div class="w-6 h-6 rounded-full cursor-pointer peer-checked:ring-2 peer-checked:ring-offset-2 peer-checked:ring-blue-500" style="background-color: <%= color %>"></div>
          </label>
        <% end %>
      </div>
      <div class="relative flex items-center border border-gray-200 rounded-lg">
        <%= f.text_field :name, placeholder: t(".placeholder"), required: true, autofocus: true, data: { color_avatar_target: "name" } %>
      </div>
    </section>

    <section>
      <%= hidden_field_tag :transaction_id, params[:transaction_id] %>
      <%= f.submit %>
    </section>
  <% end %>
</div>

app/views/categories/_menu.html.erb
<%# locals: (transaction:, origin: nil) %>
<div class="relative" data-controller="menu">
  <button data-menu-target="button" class="flex cursor-pointer">
    <%= render partial: "categories/badge", locals: { category: transaction.category } %>
  </button>
  <div data-menu-target="content" class="absolute z-10 hidden w-screen mt-2 max-w-min cursor-default">
    <div class="w-64 text-sm font-semibold leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
      <%= turbo_frame_tag "category_dropdown", src: category_dropdown_path(category_id: transaction.category_id, transaction_id: transaction.id, origin: origin), loading: :lazy do %>
        <div class="p-6 flex items-center justify-center">
          <p class="text-sm text-gray-500 animate-pulse"><%= t(".loading") %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_ruler.html.erb
<div class="bg-white">
  <div class="h-px bg-alpha-black-50 ml-4 mr-6"></div>
</div>

app/views/categories/edit.html.erb
<%= modal_form_wrapper title: t(".edit") do %>
  <%= render "form", category: @category %>
<% end %>

app/views/categories/index.html.erb
<% content_for :sidebar do %>
  <%= render "settings/nav" %>
<% end %>

<section class="space-y-4">
  <header class="flex items-center justify-between">
    <h1 class="text-gray-900 text-xl font-medium"><%= t(".categories") %></h1>

    <%= link_to new_category_path, class: "btn btn--primary flex items-center gap-1 justify-center", data: { turbo_frame: :modal } do %>
      <%= lucide_icon "plus", class: "w-5 h-5" %>
      <p><%= t(".new") %></p>
    <% end %>
  </header>

  <div class="bg-white shadow-xs border border-alpha-black-25 rounded-xl p-4">
    <% if @categories.any? %>
      <div class="rounded-xl bg-gray-25 space-y-1 p-1">
        <div class="flex items-center gap-1.5 px-4 py-2 text-xs font-medium text-gray-500 uppercase">
          <p><%= t(".categories") %></p>
          <span class="text-gray-400">&middot;</span>
          <p><%= @categories.count %></p>
        </div>

        <div class="border border-alpha-black-25 rounded-md bg-white shadow-xs">
          <div class="overflow-hidden rounded-md">
            <%= render partial: @categories, spacer_template: "categories/ruler" %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="flex justify-center items-center py-20">
        <div class="text-center flex flex-col items-center max-w-[300px]">
          <p class="text-gray-900 mb-1 font-medium text-sm"><%= t(".empty") %></p>
          <%= link_to new_category_path, class: "w-fit flex text-white text-sm font-medium items-center gap-1 bg-gray-900 rounded-lg p-2 pr-3", data: { turbo_frame: "modal" } do %>
            <%= lucide_icon("plus", class: "w-5 h-5") %>
            <span><%= t(".new") %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= settings_nav_footer %>
</section>

app/views/categories/new.html.erb
<%= modal_form_wrapper title: t(".new_category") do %>
  <%= render "form", category: @category %>
<% end %>