config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => "good_job"

  get "changelog", to: "pages#changelog"
  get "feedback", to: "pages#feedback"
  get "early-access", to: "pages#early_access"

  resource :registration, only: %i[new create]
  resources :sessions, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]

  resources :users, only: %i[update destroy]

  resource :onboarding, only: :show do
    collection do
      get :profile
      get :preferences
    end
  end

  namespace :settings do
    resource :profile, only: :show
    resource :preferences, only: :show
    resource :hosting, only: %i[show update]
    resource :billing, only: :show
  end

  resource :subscription, only: %i[new show] do
    get :success, on: :collection
  end

  resources :tags, except: :show do
    resources :deletions, only: %i[new create], module: :tag
  end

  namespace :category do
    resource :dropdown, only: :show
  end

  resources :categories do
    resources :deletions, only: %i[new create], module: :category
  end

  resources :merchants, only: %i[index new create edit update destroy]

  namespace :account do
    resources :transfers, only: %i[new create destroy show update]
  end

  resources :imports, only: %i[index new show create destroy] do
    post :publish, on: :member

    resource :upload, only: %i[show update], module: :import
    resource :configuration, only: %i[show update], module: :import
    resource :clean, only: :show, module: :import
    resource :confirm, only: :show, module: :import

    resources :rows, only: %i[show update], module: :import
    resources :mappings, only: :update, module: :import
  end

  resources :accounts, only: %i[index new] do
    collection do
      get :summary
      get :list
      post :sync_all
    end

    member do
      post :sync
    end

    scope module: :account do
      resources :holdings, only: %i[index new show destroy]
      resources :cashes, only: :index

      resources :transactions, only: %i[index update]
      resources :valuations, only: %i[index new create]
      resources :trades, only: %i[index new create update] do
        get :securities, on: :collection
      end

      resources :entries, only: %i[index edit update show destroy]
    end
  end

  # Convenience routes for polymorphic paths
  # Example: account_path(Account.new(accountable: Depository.new)) => /depositories/123
  direct :account do |model, options|
    route_for model.accountable_name, model, options
  end
  direct :edit_account do |model, options|
    route_for "edit_#{model.accountable_name}", model, options
  end

  resources :depositories, except: :index
  resources :investments, except: :index
  resources :properties, except: :index
  resources :vehicles, except: :index
  resources :credit_cards, except: :index
  resources :loans, except: :index
  resources :cryptos, except: :index
  resources :other_assets, except: :index
  resources :other_liabilities, except: :index

  resources :transactions, only: %i[index new create] do
    collection do
      post "bulk_delete"
      get "bulk_edit"
      post "bulk_update"
      post "mark_transfers"
      post "unmark_transfers"
    end
  end

  resources :institutions, except: %i[index show] do
    post :sync, on: :member
  end
  resources :invite_codes, only: %i[index create]

  resources :issues, only: :show

  namespace :issue do
    resources :exchange_rate_provider_missings, only: :update
  end

  resources :invitations, only: [ :new, :create ] do
    get :accept, on: :member
  end

  # For managing self-hosted upgrades and release notifications
  resources :upgrades, only: [] do
    member do
      post :acknowledge
      post :deploy
    end
  end

  resources :currencies, only: %i[show]

  resources :impersonation_sessions, only: [ :create ] do
    post :join, on: :collection
    delete :leave, on: :collection

    member do
      put :approve
      put :reject
      put :complete
    end
  end

  # Stripe webhook endpoint
  post "webhooks/stripe", to: "webhooks#stripe"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/controllers/account/transactions_controller.rb
class Account::TransactionsController < ApplicationController
  layout :with_sidebar

  before_action :set_account
  before_action :set_entry, only: :update

  def index
    @pagy, @entries = pagy(
      @account.entries.account_transactions.reverse_chronological,
      limit: params[:per_page] || "10"
    )
  end

  def update
    prev_amount = @entry.amount
    prev_date = @entry.date

    @entry.update!(entry_params.except(:origin))
    @entry.sync_account_later if prev_amount != @entry.amount || prev_date != @entry.date

    respond_to do |format|
      format.html { redirect_to account_entry_path(@account, @entry), notice: t(".success") }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          @entry,
          partial: "account/entries/entry",
          locals: entry_locals.merge(entry: @entry)
        )
      end
    end
  end

  private
    def set_account
      @account = Current.family.accounts.find(params[:account_id])
    end

    def set_entry
      @entry = @account.entries.find(params[:id])
    end

    def entry_locals
      {
        selectable: entry_params[:origin].present?,
        show_balance: entry_params[:origin] == "account",
        origin: entry_params[:origin]
      }
    end

    def entry_params
      params.require(:account_entry)
            .permit(
              :name, :date, :amount, :currency, :excluded, :notes, :entryable_type, :nature, :origin,
              entryable_attributes: [
                :id,
                :category_id,
                :merchant_id,
                { tag_ids: [] }
              ]
            ).tap do |permitted_params|
              nature = permitted_params.delete(:nature)

              if permitted_params[:amount]
                amount_value = permitted_params[:amount].to_d

                if nature == "income"
                  amount_value *= -1
                end

                permitted_params[:amount] = amount_value
              end
            end
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  layout :with_sidebar

  def index
    @q = search_params
    result = Current.family.entries.account_transactions.search(@q).reverse_chronological
    @pagy, @transaction_entries = pagy(result, limit: params[:per_page] || "50")

    @totals = {
      count: result.select { |t| t.currency == Current.family.currency }.count,
      income: result.income_total(Current.family.currency).abs,
      expense: result.expense_total(Current.family.currency)
    }
  end

  def new
    @entry = Current.family.entries.new(entryable: Account::Transaction.new).tap do |e|
      if params[:account_id]
        e.account = Current.family.accounts.find(params[:account_id])
        e.currency = e.account.currency
      else
        e.currency = Current.family.currency
      end
    end
  end

  def create
    @entry = Current.family
                    .accounts
                    .find(params[:account_entry][:account_id])
                    .entries
                    .create!(transaction_entry_params.merge(amount: amount))

    @entry.sync_account_later
    redirect_back_or_to @entry.account, notice: t(".success")
  end

  def bulk_delete
    destroyed = Current.family.entries.destroy_by(id: bulk_delete_params[:entry_ids])
    redirect_back_or_to transactions_url, notice: t(".success", count: destroyed.count)
  end

  def bulk_edit
  end

  def bulk_update
    updated = Current.family
                     .entries
                     .where(id: bulk_update_params[:entry_ids])
                     .bulk_update!(bulk_update_params)

    redirect_back_or_to transactions_url, notice: t(".success", count: updated)
  end

  def mark_transfers
    Current.family
      .entries
      .where(id: bulk_update_params[:entry_ids])
           .mark_transfers!

    redirect_back_or_to transactions_url, notice: t(".success")
  end

  def unmark_transfers
    Current.family
      .entries
      .where(id: bulk_update_params[:entry_ids])
           .update_all marked_as_transfer: false

    redirect_back_or_to transactions_url, notice: t(".success")
  end

  private

    def amount
      if nature.income?
        transaction_entry_params[:amount].to_d * -1
      else
        transaction_entry_params[:amount].to_d
      end
    end

    def nature
      params[:account_entry][:nature].to_s.inquiry
    end

    def bulk_delete_params
      params.require(:bulk_delete).permit(entry_ids: [])
    end

    def bulk_update_params
      params.require(:bulk_update).permit(:date, :notes, :category_id, :merchant_id, entry_ids: [])
    end

    def search_params
      params.fetch(:q, {})
            .permit(:start_date, :end_date, :search, :amount, :amount_operator, accounts: [], account_ids: [], categories: [], merchants: [], types: [], tags: [])
    end

    def transaction_entry_params
      params.require(:account_entry)
            .permit(:name, :date, :amount, :currency, :entryable_type, entryable_attributes: [ :category_id ])
            .with_defaults(entryable_type: "Account::Transaction", entryable_attributes: {})
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_search_filters
    [
      { key: "account_filter", icon: "layers" },
      { key: "date_filter", icon: "calendar" },
      { key: "type_filter", icon: "tag" },
      { key: "amount_filter", icon: "hash" },
      { key: "category_filter", icon: "shapes" },
      { key: "tag_filter", icon: "tags" },
      { key: "merchant_filter", icon: "store" }
    ]
  end

  def get_transaction_search_filter_partial_path(filter)
    "transactions/searches/filters/#{filter[:key]}"
  end

  def get_default_transaction_search_filter
    transaction_search_filters[0]
  end

  def transactions_path_without_param(param_key, param_value)
    updated_params = request.query_parameters.deep_dup

    q_params = updated_params[:q] || {}

    current_value = q_params[param_key]
    if current_value.is_a?(Array)
      q_params[param_key] = current_value - [ param_value ]
    else
      q_params.delete(param_key)
    end

    updated_params[:q] = q_params

    transactions_path(updated_params)
  end
end

app/views/transactions/_form.html.erb
<%= styled_form_with model: @entry, url: transactions_path, class: "space-y-4", data: { turbo_frame: "_top" } do |f| %>
  <section>
    <fieldset class="bg-gray-50 rounded-lg p-1 grid grid-flow-col justify-stretch gap-x-2">
      <%= radio_tab_tag form: f, name: :nature, value: :expense, label: t(".expense"), icon: "minus-circle", checked: params[:nature] == "expense" || params[:nature].nil? %>
      <%= radio_tab_tag form: f, name: :nature, value: :income, label: t(".income"), icon: "plus-circle", checked: params[:nature] == "income" %>
      <%= link_to new_account_transfer_path, data: { turbo_frame: :modal }, class: "flex px-4 py-1 rounded-lg items-center space-x-2 justify-center text-gray-400 group-has-[:checked]:bg-white group-has-[:checked]:text-gray-800 group-has-[:checked]:shadow-sm" do %>
        <%= lucide_icon "arrow-right-left", class: "w-5 h-5" %>
        <%= tag.span t(".transfer") %>
      <% end %>
    </fieldset>
  </section>

  <section class="space-y-2">
    <%= f.text_field :name, label: t(".description"), placeholder: t(".description_placeholder"), required: true %>
    <%= f.collection_select :account_id, Current.family.accounts.alphabetically, :id, :name, { prompt: t(".account_prompt"), label: t(".account") }, required: true %>
    <%= f.money_field :amount, label: t(".amount"), required: true %>
    <%= f.hidden_field :entryable_type, value: "Account::Transaction" %>
    <%= f.fields_for :entryable do |ef| %>
      <%= ef.collection_select :category_id, Current.family.categories.alphabetically, :id, :name, { prompt: t(".category_prompt"), label: t(".category") } %>
    <% end %>
    <%= f.date_field :date, label: t(".date"), required: true, min: Account::Entry.min_supported_date, max: Date.current, value: Date.current %>
  </section>

  <section>
    <%= f.submit t(".submit") %>
  </section>
<% end %>

app/views/transactions/_header.html.erb
<header class="flex justify-between items-center text-gray-900 font-medium">
  <h1 class="text-xl">Transactions</h1>
  <div class="flex items-center gap-5">
    <div class="flex items-center gap-2">
      <%= contextual_menu do %>
        <div class="w-48 p-1 text-sm leading-6 text-gray-900 bg-white shadow-lg shrink rounded-xl ring-1 ring-gray-900/5">
          <%= contextual_menu_modal_action_item t(".edit_categories"), categories_path, icon: "shapes", turbo_frame: :_top %>
          <%= contextual_menu_modal_action_item t(".edit_tags"), tags_path, icon: "tags", turbo_frame: :_top %>
          <%= contextual_menu_modal_action_item t(".edit_merchants"), merchants_path, icon: "store", turbo_frame: :_top %>
          <%= contextual_menu_modal_action_item t(".edit_imports"), imports_path, icon: "hard-drive-upload", turbo_frame: :_top %>
        </div>
      <% end %>

      <%= link_to new_import_path, class: "btn btn--outline flex items-center gap-2", data: { turbo_frame: "modal" } do %>
        <%= lucide_icon("download", class: "text-gray-500 w-4 h-4") %>
        <p class="text-sm font-medium text-gray-900"><%= t(".import") %></p>
      <% end %>

      <%= link_to new_transaction_path, class: "rounded-lg bg-gray-900 text-white flex items-center gap-1 justify-center hover:bg-gray-700 px-3 py-2", data: { turbo_frame: :modal } do %>
        <%= lucide_icon("plus", class: "w-5 h-5") %>
        <p class="text-sm font-medium">New transaction</p>
      <% end %>
    </div>
  </div>
</header>

app/views/transactions/_summary.html.erb
<%# locals: (totals:) %>
<div class="grid grid-cols-3 bg-white rounded-xl border border-alpha-black-25 shadow-xs divide-x divide-alpha-black-100">
  <div class="p-4 space-y-2">
    <p class="text-sm text-gray-500">Total transactions</p>
    <p class="text-gray-900 font-medium text-xl" id="total-transactions"><%= totals[:count] %></p>
  </div>
  <div class="p-4 space-y-2">
    <p class="text-sm text-gray-500">Income</p>
    <p class="text-gray-900 font-medium text-xl" id="total-income">
      <%= format_money totals[:income] %>
    </p>
  </div>
  <div class="p-4 space-y-2">
    <p class="text-sm text-gray-500">Expenses</p>
    <p class="text-gray-900 font-medium text-xl" id="total-expense">
      <%= format_money totals[:expense] %>
    </p>
  </div>
</div>

app/views/transactions/bulk_edit.html.erb
<%= turbo_frame_tag "bulk_transaction_edit_drawer" do %>
  <dialog data-controller="modal"
          data-action="click->modal#clickOutside"
          class="bg-white border border-alpha-black-25 rounded-2xl max-h-[calc(100vh-32px)] max-w-[480px] w-full shadow-xs h-full mt-4 mr-4">
    <%= styled_form_with url: bulk_update_transactions_path, scope: "bulk_update", class: "h-full", data: { turbo_frame: "_top" } do |form| %>
      <div class="flex h-full flex-col justify-between p-4">
        <div>
          <div class="flex h-9 items-center justify-end">
            <div data-action="click->modal#close" class="cursor-pointer">
              <%= lucide_icon("x", class: "w-5 h-5 shrink-0") %>
            </div>
          </div>

          <div class="flex flex-col overflow-scroll">
            <div>
              <header class="mb-4 space-y-1">
                <h3 class="text-2xl font-medium" data-bulk-select-target="bulkEditDrawerTitle">
                  Edit transactions
                </h3>
              </header>

              <div class="space-y-2">
                <details class="group space-y-2" open>
                  <summary class="flex list-none items-center justify-between rounded-xl px-3 py-2 text-xs font-medium uppercase text-gray-500 bg-gray-25 focus-visible:outline-none">
                    <h4><%= t(".overview") %></h4>
                    <%= lucide_icon "chevron-down", class: "group-open:transform group-open:rotate-180 text-gray-500 w-5" %>
                  </summary>

                  <div class="pb-6 space-y-2">
                    <%= form.date_field :date, label: t(".date_label"), max: Date.current %>
                  </div>
                </details>

                <details class="group space-y-2" open>
                  <summary class="flex list-none items-center justify-between rounded-xl px-3 py-2 text-xs font-medium uppercase text-gray-500 bg-gray-25 focus-visible:outline-none">
                    <h4><%= t(".details") %></h4>
                    <%= lucide_icon "chevron-down", class: "group-open:transform group-open:rotate-180 text-gray-500 w-5" %>
                  </summary>

                  <div class="space-y-2">
                    <%= form.collection_select :category_id, Current.family.categories.alphabetically, :id, :name, { prompt: t(".category_placeholder"), label: t(".category_label"), class: "text-gray-400" } %>
                    <%= form.collection_select :merchant_id, Current.family.merchants.alphabetically, :id, :name, { prompt: t(".merchant_placeholder"), label: t(".merchant_label"), class: "text-gray-400" } %>
                    <%= form.text_area :notes, label: t(".note_label"), placeholder: t(".note_placeholder"), rows: 5 %>
                  </div>
                </details>
              </div>
            </div>
          </div>
        </div>

        <div class="flex justify-end items-center gap-2">
          <%= link_to t(".cancel"), transactions_path, class: "text-sm font-medium text-gray-900 px-3 py-2" %>

          <%= tag.button t(".save"),
                         type: "button",
                         data: { "bulk-select-scope-param": "bulk_update", action: "bulk-select#submitBulkRequest" },
                         class: "px-3 py-2 bg-gray-900 text-white text-sm font-medium rounded-lg" %>
        </div>
      </div>
    <% end %>
  </dialog>
<% end %>

app/views/transactions/index.html.erb
<div class="space-y-4 h-full flex flex-col overflow-y-auto">
  <%= render "header" %>

  <%= render "summary", totals: @totals %>

  <div id="transactions"
       data-controller="bulk-select"
       data-bulk-select-singular-label-value="<%= t(".transaction") %>"
       data-bulk-select-plural-label-value="<%= t(".transactions") %>"
       class="overflow-y-auto flex flex-col bg-white rounded-xl border border-alpha-black-25 shadow-xs p-4">
    <%= render "transactions/searches/search" %>

    <% if @transaction_entries.present? %>
      <div id="entry-selection-bar" data-bulk-select-target="selectionBar" class="flex justify-center hidden">
        <%= render "account/transactions/selection_bar" %>
      </div>
      <div class="grow overflow-y-auto">
        <div class="grid grid-cols-12 bg-gray-25 rounded-xl px-5 py-3 text-xs uppercase font-medium text-gray-500 items-center mb-4">
          <div class="pl-0.5 col-span-6 flex items-center gap-4">
            <%= check_box_tag "selection_entry",
                              class: "maybe-checkbox maybe-checkbox--light",
                              data: { action: "bulk-select#togglePageSelection" } %>
            <p class="col-span-4">transaction</p>
          </div>

          <p class="col-span-2">category</p>
          <p class="col-span-2">account</p>
          <p class="col-span-2 justify-self-end">amount</p>
        </div>
        <div class="space-y-6">
          <%= entries_by_date(@transaction_entries, totals: true) do |entries| %>
            <%= render entries, origin: "transactions" %>
          <% end %>
        </div>
      </div>
    <% else %>
      <%= render "account/entries/empty" %>
    <% end %>

    <div class="pt-4">
      <%= render "pagination", pagy: @pagy %>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<%= modal_form_wrapper title: t(".new_transaction") do %>
  <%= render "form", transaction: @transaction, entry: @entry %>
<% end %>

app/views/transactions/rules.html.erb
<% content_for :sidebar do %>
  <%= render "settings/nav" %>
<% end %>

<div class="space-y-4">
  <h1 class="text-gray-900 text-xl font-medium mb-4">Rules</h1>
  <div class="bg-white shadow-xs border border-alpha-black-25 rounded-xl p-4">
    <div class="flex justify-center items-center py-20">
      <p class="text-gray-500">Transaction rules coming soon...</p>
    </div>
  </div>
  <div class="flex justify-between gap-4">
    <%= previous_setting("Merchants", merchants_path) %>
    <%= next_setting("Imports", imports_path) %>
  </div>
</div>